version: "3.9"

services:

  db:
    image: postgis/postgis:16-3.4
    container_name: itineraire_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file: .env
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/app
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
    env_file: .env
    environment:
      API_BASE_URL: http://api:8000
      PYTHONPATH: /app/src
      DT_PATH: /app/sources/df_datatourisme_france_prime.parquet
      AB_PATH: /app/sources/df_airbnb_paris.parquet
      TA_PATH: /app/sources/df_tripadvisor_france.parquet
    volumes:
      - .:/app
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8501:8501"
    working_dir: /app
    command: streamlit run /app/docker/ui/app.py --server.port=8501 --server.address=0.0.0.0

  scheduler:
    build:
      context: .
      dockerfile: docker/cron/Dockerfile
    env_file: .env
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app


  # ETL exécuté une seule fois au démarrage
  init:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file: .env
    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/app
      - ./sources:/app/sources
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    command: python -u /app/src/pipelines/run_etl.py 

volumes:
  db_data:
